// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://example.com/terms/",
        "contact": {
            "name": "API Support",
            "email": "kerhael.me@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/categories/": {
            "get": {
                "description": "Retrieve all categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create a category",
                "parameters": [
                    {
                        "description": "Category payload",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/categories/{id}": {
            "get": {
                "description": "Retrieve a category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get a category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete a category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Check server and database connectivity",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/": {
            "get": {
                "description": "Retrieve all outcomes with optional date filtering (defaults to current month if not provided)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get all outcomes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date filter (ISO 8601 format, defaults to first day of current month)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (ISO 8601 format, defaults to now)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.OutcomeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new outcome",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Create an outcome",
                "parameters": [
                    {
                        "description": "Outcome payload",
                        "name": "outcome",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateOutcomeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.OutcomeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/series-by-category": {
            "get": {
                "description": "Get the sum of outcomes by category for each month between dates (defaults to last 12 months if not provided)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get monthly series of outcomes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date filter (ISO 8601 format, defaults to 12 months ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (ISO 8601 format, defaults to now)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/domain.MonthlySeries"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/series-total": {
            "get": {
                "description": "Get the total sum of outcomes for each month between dates (defaults to last 12 months if not provided)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get monthly series of outcomes' total amount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date filter (ISO 8601 format, defaults to 12 months ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (ISO 8601 format, defaults to now)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/domain.MonthlyTotalSeries"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/sums-by-category": {
            "get": {
                "description": "Get the total amount of outcomes by category between dates (defaults to current month if not provided), optionally filtered by category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get sum of outcomes by category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date filter (ISO 8601 format, defaults to first day of current month)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (ISO 8601 format, defaults to now)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Category ID filter",
                        "name": "categoryId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.CategorySumResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/total": {
            "get": {
                "description": "Get the total amount of outcomes between dates (defaults to current month if not provided)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get total of outcomes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date filter (ISO 8601 format, defaults to first day of current month)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (ISO 8601 format, defaults to now)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.TotalOutcomeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/outcomes/{id}": {
            "get": {
                "description": "Retrieve an outcome by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Get an outcome",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Outcome ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.OutcomeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an outcome by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Delete an outcome",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Outcome ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an outcome",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "outcomes"
                ],
                "summary": "Update an outcome",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Outcome ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Outcome payload",
                        "name": "outcome",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PatchOutcomeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.OutcomeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "domain.MonthlySeries": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "Map of categoryId to total amount",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "month": {
                    "description": "Month in YYYY-MM format",
                    "type": "string"
                }
            }
        },
        "domain.MonthlyTotalSeries": {
            "type": "object",
            "properties": {
                "month": {
                    "description": "Month in YYYY-MM format",
                    "type": "string"
                },
                "total": {
                    "description": "Total amount",
                    "type": "integer"
                }
            }
        },
        "v1.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "v1.CategorySumResponse": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "description": "Category ID",
                    "type": "integer"
                },
                "total": {
                    "description": "Total amount in cents for this category",
                    "type": "integer"
                }
            }
        },
        "v1.CreateCategoryRequest": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                }
            }
        },
        "v1.CreateOutcomeRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount in cents (ex: 1999 for 19.99€)",
                    "type": "integer"
                },
                "categoryId": {
                    "description": "ID of the associated category",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Date of the expense (ex: \"2026-01-01T00:00:00Z\")",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the expense",
                    "type": "string"
                }
            }
        },
        "v1.OutcomeResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount in cents (ex: 1999 for 19.99€)",
                    "type": "integer"
                },
                "categoryId": {
                    "description": "ID of the associated category",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Date of the expense (ex: \"2026-01-01T00:00:00Z\")",
                    "type": "string"
                },
                "id": {
                    "description": "ID of the expense",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the expense",
                    "type": "string"
                }
            }
        },
        "v1.PatchOutcomeRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount in cents (optional, ex: 1999 for 19.99€)",
                    "type": "integer"
                },
                "categoryId": {
                    "description": "ID of the associated category (optional)",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Date of the expense (optional, ex: \"2026-01-01T00:00:00Z\")",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the expense (optional)",
                    "type": "string"
                }
            }
        },
        "v1.TotalOutcomeResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "description": "Total amount in cents",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1/",
	Schemes:          []string{"http"},
	Title:            "Accounting API",
	Description:      "API de suivi de comptabilité",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
