name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: accounting
          POSTGRES_PASSWORD: password
          POSTGRES_DB: accounting
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U accounting"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: accounting
      DB_PASSWORD: password
      DB_NAME: accounting
      DB_SSLMODE: disable

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26
      
      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod download

      - name: Install migrate
        run: go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrations
        run: |
          migrate -path migrations \
          -database "postgres://accounting:accounting@localhost:5432/accounting?sslmode=disable" up

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run tests
        run: go test ./...