name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: accounting
          POSTGRES_PASSWORD: accounting
          POSTGRES_DB: accounting
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U accounting"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: accounting
      DB_PASSWORD: accounting
      DB_NAME: accounting
      DB_SSLMODE: disable

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26
      
      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod download

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz
          tar -xzf migrate.tar.gz
          sudo mv migrate /usr/local/bin/
          migrate -version

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U accounting; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run migrations
        run: |
          migrate -path migrations \
          -database "postgres://accounting:accounting@localhost:5432/accounting?sslmode=disable" up

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
      - name: Lint
        run: golangci-lint run

      - name: Run tests
        run: go test ./...